name: Deploy blog from Obsidian

on:
  push:
    branches:
      - main

jobs:
  publish_job:
    runs-on: ubuntu-latest
    name: Publish Obsidian notes to Github pages
    steps:
      - uses: haxrob/obsidian-to-hugo-pages@v0.1.3
        with:
          external-repository: ""
          vault-path: documentation
          github-token: ${{ secrets.GITHUB_TOKEN }}